name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -scheme ImageDownloader -allowProvisioningUpdates
    - name: Run tests
      run: xcodebuild -scheme ImageDownloader -destination 'platform=iOS Simulator,name=iPhone 8' test -allowProvisioningUpdates
